### ISSUE TITLE
Make warehouse uploads global

### ISSUE THREAD

**Issue by Yossi** [Yossi/cwtgbot#21]
Added authentication as of 7de153f4fe7fd4f5d8db126bcc4a46e85249f44d

Next step is to store it in bot memory (or whatever it's called) instead of user_data

**Comment by Yossi** [comment]
chat_data is not where it goes either.

need to create custom outside data storage for this.

**Comment by keithel** [comment]
Yossi, [06.12.19 18:15]
I didn't check in the chat_data change

Keith, [06.12.19 18:15]
Kk

Yossi, [06.12.19 18:18]
Relevant places are in brains.py. warehouse_in() (lines 175 & 198) and warehouse_crafting() (line 237)

Yossi, [06.12.19 18:19]
Note that almost everything in brains.py is inside the function main() but warehouse_crafting() is outside.

Yossi, [06.12.19 18:20]
Bit of a weird design. It just happened
