### ISSUE TITLE
Craft withdraw

### ISSUE THREAD

**Issue by keithel** [Yossi/cwtgbot#24]
Feature that allows user to request crafting a specific item, either with desired crafted item quantity, or  without any quantity.

- Define user command syntax (ex: `/craft_withdraw <item #> <qty desired>` )
- Include recipes that can be looked up, or, allow bot to request the recipe from another bot (?). <-- Best specified as a separate, to be created issue.
- Query guild stock or cached guild stock to identify how many items can be made.
- Generate `/g_withdraw` command and return to the user.

**Comment by Yossi** [comment]
#19 is related
