### ISSUE TITLE
Sort items within /g_withdraw commands

### ISSUE THREAD

**Issue by the-daveman** [Yossi/cwtgbot#46]
Currently: the withdraw contents appear arbitrarily sorted.

> /g_withdraw 17 1 31 11 35 14 36 9 23 11 37 1 16 3 13 9 15 1

Change: sort withdraw contents in descending numerical order

> /g_withdraw 37 1 36 9 35 14 31 11 23 11 17 1 16 3 15 1 13 9 

This makes it much easier to visually diff the withdraw commands

**Comment by Yossi** [comment]
Should be sorted now for crafting lookups.
As I understand it, this is really where sorting is needed, not all places.
